#!/bin/bash
COLUMN=ipmi
DETAILSFILE="${BBTMP}/ipmi.log"
LOCATIONLINE="This message generated by `pwd`/`basename $0` on `hostname --fqdn`"


echo "Sensor Data Repository:"
ipmitool sdr 2>&1 |egrep -v "Chassis Intr|PS Status" |while read line
 do
        if [[ $line =~ (ok)$ ]] ; then
               echo "&green $line"
        elif [[ $line =~ (ns)$ ]] ; then
               echo "&clear $line"
        else [[ $line =~ "Could not open device" ]]
                color=yellow
	fi

done >> $DETAILSFILE

DETAILS=`cat $DETAILSFILE`
$BB $BBDISP "status $MACHINE.$COLUMN $COLOR `date`
${MSGLINE}

${DETAILS}

$LOCATIONLINE
"

rm "$DETAILSFILE"
