#!/bin/bash

echo "Sensor Data Repository:"

results=ipmitool sdr 2>&1 |egrep -v "Chassis Intr|PS Status" | while read line
 do
        if [[ $line == *ok ]] ; then
                "green" $line
        elif [[ $line == *ns ]] ; then
                clear $line
        elif [[ $line == Could not open device* ]]
                yellow
        fi

done 

echo " $results"
