#!/bin/bash

function isnum() {
a=$1
[ ! -z "${a##[0-9]*}" ] && a=U
[ -z "$a" ] && a=U
echo $a
}

function ucheck() {
if [[ "$1"   =~ U ]]
then
 echo "U"
else
 echo ""
fi
}

id='cass'
filter='org.apache.cassandra.request'
cd `dirname $0`
host=`hostname`
port=7199
count=1
MSG=""

while read line
do
 if [[ ! "$line" =~ $filter ]]; then
	continue
 fi
 echo $line
 ret=`echo $line | awk '{split($1,vars,",");for (i in vars)c++}END {c--;print(c); }'`
 #echo "here count is $ret"
	
 class=`echo $line|awk -F'\\\|\\\|' '{print $1}'`
# echo "class=>$class"
 attribute=`echo $line|awk -F'\\\|\\\|' '{print $2}'`
# echo "attr ==> $attribute"
 javacmd="java  -classpath nagtomcat.jar com.groundworkopensource.tomcat.nagios.plugin.Shell  -s $host -p $port -m $class -a $attribute"
 if [ $ret -eq 0 ]; then
   tmp=`$javacmd | awk -F= '{print $3}'`
   tmp=`echo $tmp|sed 's/^ *//'`
   eval v$count=$tmp
 elif [ $ret -eq 1 ]; then
   tmp=`$javacmd | awk -F= '{print $4}'`
   tmp=`echo $tmp|sed 's/^ *//'`
   eval v$count=$tmp
 elif [ $ret -eq 2 ]; then
   tmp=`$javacmd | awk -F= '{print $5}'`
   tmp=`echo $tmp|sed 's/^ *//'`
   eval v$count=$tmp
 fi
	
 #eval echo  "here1 \$v$count"
 eval v$count=`isnum $tmp`
 #eval echo "here2 got \$v$count"
 eval echo "$class $attribute \$v$count">>/tmp/$0.$$
 count=`expr $count + 1`

done < ${id}.yml.tab


COLUMN=cass_request
COLOUR=green
[ "`ucheck "${v1}${v2}${v3}${v4}"`" = "U" ] && COLOUR=yellow

MACHINE=`echo $host | tr '.' ','`
$BB $BBDISP "status $MACHINE.$COLUMN $COLOUR `date`

`cat /tmp/$0.$$`

This message generated by `pwd`/`basename $0` on `hostname --fqdn`
"
rm /tmp/$0.$$
exit 0

