#!/bin/bash


##############################################
# Location Msg line setup
cd `dirname $0`

LOCATIONLINE="This message generated by `pwd`/`basename $0` on `hostname --fqdn`"


# Name of our script for debugging purposes
#
#BBPROG=hardware.sh; export BBPROG

# Set these for testing if you need to
#
#BBHOME=/home/bb/bb; export BBHOME


############################################
#Check theat we have the ENV and tools to do what we need to
#

if test "$BBHOME" = ""; then
  echo "BBHOME is not set...exiting"
  exit 1
fi


###########################################
#Setup Infrastructure for tests
#
#
# Collect data regarding the system from the commands
#
HPCPU=$BBTMP/cpu.hp
HPMEMORY=$BBTMP/memory.hp
HPPOWER=$BBTMP/power.hp
HPFANS=$BBTMP/fans.hp
HPTEMPS=$BBTMP/temps.hp
#

##########
### Comence Testing CPU
##########
sudo /sbin/hpasmcli -s 'SHOW SERVER' > $HPCPU
if grep Status $HPCPU | grep -q -v Ok; then
    COLOR="red"
    MSGLINE="WARNING: A harware problem has been detected"
else
    COLOR="green"
    MSGLINE="Everything is OK"
fi
DETAILS=`cat ${HPCPU}`
$BB $BBDISP "status $MACHINE.hp_cpu $COLOR `date`
${MSGLINE}


$DETAILS

$LOCATIONLINE
"
##########
### Comence Checking Memory
##########

sudo /sbin/hpasmcli -s 'SHOW DIMM' > $HPMEMORY
if grep Status $HPMEMORY | grep -q -v Ok; then
    if grep Status $HPMEMORY | grep -q "DIMM is degraded"; then
        COLOR="yellow"
	MSGLINE="Degraded DIM"
    else
        COLOR="red"
    fi
    MSGLINE="WARNING: A harware problem has been detected"
    cat $HPMEMORY
else
    COLOR="green"
fi
DETAILS=`cat ${HPMEMORY}`
$BB $BBDISP "status $MACHINE.hp_mem $COLOR `date`
${MSGLINE}

$DETAILS

$LOCATIONLINE
"
##########
### Comence Testing POWER
##########

sudo /sbin/hpasmcli -s 'SHOW POWERSUPPLY' > $HPPOWER
if grep Condition $HPPOWER | grep -q -v Ok; then
    COLOR="red"
    MSGLINE="WARNING: A harware problem has been detected"
else
    COLOR="green"
fi
DETAILS=`cat ${HPPOWER}`
$BB $BBDISP "status $MACHINE.hp_pwr $COLOR `date`
${MSGLINE}

$DETAILS


$LOCATIONLINE
"
##########
### Comence Checking FANS
##########

sudo /sbin/hplog -f > $HPFANS
if grep -v STATUS $HPFANS | grep -v "^$" | cut -b 34-40 | grep -q -v Normal; then
    COLOR="red"
    MSGLINE="WARNING: A harware problem has been detected"
else
    COLOR="green"
fi
DETAILS=`cat ${HPFANS}`
$BB $BBDISP "status $MACHINE.hp_fans $COLOR `date`
${MSGLINE}

$DETAILS


$LOCATIONLINE
"
##########
### Comence Checking Temp
##########

sudo /sbin/hplog -t > $HPTEMPS
if grep -v STATUS $HPTEMPS | grep -v "^$" | cut -b 34-40 | grep -q -v Normal; then
    COLOR="red"
    MSGLINE="WARNING: A harware problem has been detected"
else
    COLOR="green"
fi
DETAILS=`cat ${HPTEMPS}`
$BB $BBDISP "status $MACHINE.hp_temp $COLOR `date`
${MSGLINE}

$DETAILS


$LOCATIONLINE
"

exit 0
