#!/bin/bash
#########
#### Setup Section
########
cd `dirname $0`
CMDPATH="/sbin/"
COLUMN=sm_raid
COLOR="red"
LOGFILE="${BBTMP}/sm_raid.log"
LOCATIONLINE="This message generated by `pwd`/`basename $0` on `hostname --fqdn`"
read -d ' ' DISKLIST <<"EOF"
/dev/sdd
/dev/sdc
/dev/sdb
/dev/sda

EOF

##########
##### Pre-flight Checks
##########
#if test "$BBHOME" = ""; then
#  echo "BBHOME is not set...exiting"
#  exit 1
#fi

#######################
######## Functions
#######################
function dmraid {
sudo $CMD >> $LOGFILE
if [ 'grep "status" $LOGFILE |grep inconsistent' ]; then
	DISK=`dmraid -r |sort -rn| diff $DISKLIST - |grep dev |cut -c3-100`
	COLOR="red"
	MSGLINE="disk $DISK has failed"
else 
	COLOR=green
	MSGLINE="All is well"
fi
DETAILS=`cat $LOGFILE`
}

function mdstat {

if [ 'cat /proc/mdstat | grep "(F)" -eq 0' ] ; then 
	COLOR="green"
else
	COLOR="red"

fi

DETAILS=`cat /proc/mdstat`

}

if [ 'sudo /sbin/dmraid -s | grep "no raid disks"' ]; then
        mdstat
else
        dmraid
fi

$BB $BBDISP "status $MACHINE.$COLUMN $COLOR `date`
${MSGLINE}

${DETAILS}

$LOCATIONLINE
"
if [ -e $LOGFILE ]; then
	rm $LOGFILE
fi

exit 0
