#!/bin/bash
#########
#### Setup Section
########
cd `dirname $0`
CMDPATH="/usr/sbin/"
COLUMN=sm_raid
COLOR="red"
LOGFILE="${BBTMP}/sm_raid.log"
LOCATIONLINE="This message generated by `pwd`/`basename $0` on `hostname --fqdn`"
##########
##### Pre-flight Checks
##########
if test "$BBHOME" = ""; then
  echo "BBHOME is not set...exiting"
  exit 1
fi

if [ `${CMDPATH}megaraid-status|grep a0` !=1 ]; then
	CMD="/usr/sbin/megaraidsas-status"
else
	CMD="/usr/sbin/megaraid-status"
fi
#######################
######## Function
#######################
sudo $CMD >> $LOGFILE
if grep a0 $LOGFILE |grep FAILED; then
	DISK=grep FAILED $logfile
	COLOR="red"
	MSGLINE="disk $DISK has failed"
else 
	COLOR=green
	MSGLINE="All is well"
fi
DETAILS=`cat $LOGFILE`
$BB $BBDISP "status $MACHINE.$COLUMN $COLOR `date`
${MSGLINE}

${DETAILS}

$LOCATIONLINE
"
rm $LOGFILE

